[project]
name = "movie-recommender-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ltp-latypov", email = "ltp.latypov@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dlt>=1.30.0",
    "elasticsearch<9.0.0",
    "fastapi>=0.141.1",
    "gdown>=6.1.0",
    "openai>=3.0.0",
    "polars>=1.43.2",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
    "streamlit>=1.59.1",
    "torchvision>=0.28.0",
    "uvicorn>=0.52.2",
]

[project.scripts]
movie-recommender-assistant = "movie_recommender_assistant:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }
